services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - litellm_postgres_data:/var/lib/postgresql/data

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/litellm
      STORE_MODEL_IN_DB: 'True' # allows adding models to proxy via UI
      MASTER_KEY: ${LITELLM_MASTER_KEY:-sk-1234}
    env_file:
      - path: '.env.local'
        required: false
    ports:
      - '4000:4000'
    entrypoint: sh
    command: -c "litellm --config /app/etc/$${LITELLM_CONFIG_FILE:-config.yaml} --detailed_debug"
    volumes:
      - ./etc:/app/etc
    depends_on:
      - postgres
    init: true

volumes:
  litellm_postgres_data:
